name: APEX Motoru Olusturma

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Motor Zip dosyasini buluttan indirin.
      shell: powershell
      run: |
        # Catbox linkini buraya tırnakların içine yapıştır!
        Invoke-WebRequest -Uri "https://files.catbox.moe/nhyjzj.zip" -OutFile "APEX_Engine.zip"

    - name: Motor Dosyalarini Ac
      shell: powershell
      run: |
        Expand-Archive -Path .\APEX_Engine.zip -DestinationPath .\ExtractedEngine

    - name: GLFW Kutuphanesini Kur (vcpkg)
      run: vcpkg install glfw3:x64-windows

    - name: CMake'i yapilandirin
      run: cmake -B build -S .\ExtractedEngine -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Derleme Motoru
      run: cmake --build build --config Release

    - name: Derleme Yapitlarini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: APEX_Engine_Executable
        path: build/Release/

        
